create a github action pipeline

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -9,9 +9,13 @@ name: Java CI with Gradle
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "main", "develop" ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ "main", "develop" ]
+
+permissions:
+  checks: write
+  pull-requests: write # only required if `comment: true` was enabled
 
 jobs:
   build:
@@ -33,9 +37,33 @@ jobs:
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
 
+    - name: Generate weatherbit client
+      run: ./gradlew openApiGenerate
     - name: Build with Gradle Wrapper
       run: ./gradlew build
 
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/build/test-results/test/TEST-*.xml'
+        token: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Upload Test Report
+      uses: actions/upload-artifact@v4
+      if: always() # always run even if the previous step fails
+      with:
+        name: junit-test-results
+        path: '**/build/test-results/test/TEST-*.xml'
+        retention-days: 1
+
+    - name: Upload build artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: Package
+        path: '**/build/libs/*.jar'
+
+    # - name: Gradle Wrapper Validation
     # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
     # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
     #
@@ -65,3 +93,4 @@ jobs:
     # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
     - name: Generate and submit dependency graph
       uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
+
